### ISSUE TITLE
HTML5 series not working

### ISSUE THREAD

**Issue by juanteran** [makigas/makigas#43]
![HTML5](http://i.imgur.com/PwXHqhC.png "HTML5 series not working")

**Comment by danirod** [comment]
Can confirm https://www.makigas.es/series/html-basico is not working. Adding a slash at the end of the URL seems to be a workaround as https://www.makigas.es/series/html-basico/ works. Will look into this, though.

**Comment by danirod** [comment]
Fixed. This has been a *really* interesting bug.

/etc/nginx/sites-enabled/www.makigas.es had the following block for caching static resources. The purpose of this block is to change the headers used in static resources so that the web browser could cache them instead of asking the server again.

    location ~* .(woff|eot|ttf|svg|mp4|webm|jpg|jpeg|png|gif|ico|css|js)$ {
        gzip_static on;
        expires 6h;
        add_header Cache-Control public;
    }

Now, taking a closer look into the regex, there was a very critical bug on it: it lacks a \ before the dot. And this is important because, while \.ico$ matches any file finishing with `.ico` (such as /favicon.ico), .ico$ matches any file finishing with `ico`, such as /favicon.ico, **but also /series/html-basico**. That is why /series/html-basico/ works, because it breaks the regex.

I have added a backslash before the dot at the beginning of the regex and I can confirm /series/html-basico works now. No regressions as `curl -I https://www.makigas.es/favicon.ico` shows that the cache headers are being set.

I don't know where did I copy and paste this from months ago. The moral of the story is:
* Only do copy and paste from reliable sources.
* God dammit, validate whatever you copy and paste.
