### ISSUE TITLE
rails db:seeds issue

### ISSUE THREAD

**Issue by justinallenmarsh** [makigas/makigas#672]
I receive the following error when trying to run rails:seeds <img width="1693" alt="image" src="https://user-images.githubusercontent.com/48605824/159142059-9c919106-444a-4520-82a8-dd524711e41e.png">

**Comment by justinallenmarsh** [comment]
```Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/Users/j-mba/.rbenv/versions/3.0.1/lib/ruby/3.0.0/pathname.rb:20: warning: already initialized constant Pathname::TO_PATH
/Users/j-mba/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:20: warning: previous definition of TO_PATH was here
/Users/j-mba/.rbenv/versions/3.0.1/lib/ruby/3.0.0/pathname.rb:22: warning: already initialized constant Pathname::SAME_PATHS
/Users/j-mba/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:22: warning: previous definition of SAME_PATHS was here
/Users/j-mba/.rbenv/versions/3.0.1/lib/ruby/3.0.0/pathname.rb:34: warning: already initialized constant Pathname::SEPARATOR_LIST
/Users/j-mba/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:34: warning: previous definition of SEPARATOR_LIST was here
/Users/j-mba/.rbenv/versions/3.0.1/lib/ruby/3.0.0/pathname.rb:35: warning: already initialized constant Pathname::SEPARATOR_PAT
/Users/j-mba/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:35: warning: previous definition of SEPARATOR_PAT was here
/Users/j-mba/.rbenv/versions/3.0.1/lib/ruby/3.0.0/pathname.rb:41: warning: already initialized constant Pathname::ABSOLUTE_PATH
/Users/j-mba/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:41: warning: previous definition of ABSOLUTE_PATH was here
rails aborted!
Don't know how to build task 'db:seeds' (See the list of available tasks with `rails --tasks`)
Did you mean?  db:seed```

**Comment by danirod** [comment]
The name is db:seed.

**Comment by danirod** [comment]
Oh, I see that I have a typo in the README and it says db:seeds. That is an issue 💡

**Comment by justinallenmarsh** [comment]
![image](https://user-images.githubusercontent.com/48605824/159186981-83bc5b3b-83ca-4206-b40e-2102e6cb76ab.png)

**Comment by justinallenmarsh** [comment]
There are some configurations that I think you have on your personal computer which are necessary to launch the app.

**Comment by justinallenmarsh** [comment]
I tried to create a pull request to list all the changes necessary to set up the app on a new system, but it wouldn't let me push it to git.

https://gist.github.com/jmarsh24/a810445bc6e8549831d8face50f32a48

I added them to a gist for you in case it helps!

**Comment by danirod** [comment]
Yeah, a lot of things are still hardcoded to only work on my machine. The public site may look "good" at the moment, but it came at the cost of having a backend so dirty at the moment in order to finish on schedule that I'm even ashamed of this repository :D.

I'll review what to do with the database. The reason it is failing is because a role is expected to exist in PostgreSQL. In your gist, I see that the change you propose is to remove the role from config/database.yml. While this is the standard thing to do when developing on a Mac with PostgreSQL installed via Homebrew, installing PostgreSQL on a Linux box configures a more restrictive environment where roles are expected to exist anyway and have a valid password.

I think I'll just configure dotenv to make it easier to provide the system defaults, given that there are more environment variables that should be set in order to properly do development (AUTHORIZED_HOSTS, USE_SIX...).

**Comment by jmarsh24** [comment]
Did you deploy your search to Heroku or to another hosting platform?

**Comment by danirod** [comment]
Fixed in d1c6670bcf227625623c38ffefbb4f919aecf357
